version: '3.8'
networks:
  crypto-net:
    driver: bridge

services:
  app:
    build: .
    container_name: liquidation-tracker-app
    restart: unless-stopped
    networks:
      - crypto-net
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: liquidation-tracker-redis
    restart: unless-stopped
    networks:
      - crypto-net
    volumes:
      - redis_data:/data

volumes:
  redis_data: